using UnityEngine;
using UnityEngine.InputSystem;

public class quizmovement : MonoBehaviour
{
    [SerializeField] float steerspeed = 350f;
    [SerializeField] float movespeed = 7.5f;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        float move = 0f;
        float steer = 0f;

        if (Keyboard.current.wKey.isPressed)
        {
            move = 1f;
            if (Keyboard.current.aKey.isPressed)
            {
                steer = 1f;
            }
            else if (Keyboard.current.dKey.isPressed)
            {
                steer = -1f;
            }
        }
        else if (Keyboard.current.sKey.isPressed)
        {
            move = -1f;
            if (Keyboard.current.aKey.isPressed)
            {
                steer = 1f;
            }
            else if (Keyboard.current.dKey.isPressed)
            {
                steer = -1f;
            }
        }

        float moveAmount = move * movespeed * Time.deltaTime;
        float steerAmount = steer * steerspeed * Time.deltaTime;

        transform.Rotate(0, 0, steerAmount);
        transform.Translate(0, moveAmount, 0);
    }
}
